### ISSUE TITLE
# Todo 

### ISSUE THREAD

**Issue by DiegoCao** [DiegoCao/mdp2021spring#1]
- [x] Apply weight decay to both of the two models.
- [x] Examine the mixture of the model
- [x] Implement Bayesian CNN for that model
- [x] Get the previous confusion matrix of the labels

Data Description
- [x] Study the distribution of the method
- [x] Remove the 10.
- [x] Histogram
